### ISSUE TITLE
Matching engine horizontal scaling

### ISSUE THREAD

**Issue by xuganyu96** [xuganyu96/chives-exchange#27]
Design the deployment scheme where multiple matching engine instances are running.

**Comment by xuganyu96** [comment]
https://github.com/xuganyu96/chives-exchange/wiki/Benchmarking-matching-engine-performance

**Comment by xuganyu96** [comment]
I need to update my benchmark to properly verify that horizontal scaling does help improve performance:

despite the orders being submitted in pairs, it is not necessarily true that the transactions will be perfectly matching the pairs because  there can be more than one matching engines running asynchronously.

This creates the possibility that there are fewer than or more than `n_rounds` of transactions, and that there are more than `2 * n_rounds` of orders. The only way to know that all orders have been processed is by knowing that the matching engines have all finished working. Without the benchmark directly communicating with the matching engines, the best way would be to count the number of mesages in the queue, and declare end time to be when all messages have cleared in the queue. This way the end time will be at most 1 heartbeat away from the true finish time, which, because it is constant, it acceptable.

**Comment by xuganyu96** [comment]
# Try this
Modify the acknowledgement in matching engine callback such that the message queue gets acknowledgement when the worker finished processing

**Comment by xuganyu96** [comment]
# To-do's

- [ ] Implement message ack after heartbeat is finished

- [ ] Implement benchmark verification logic in `chives.benchmark.benchmark`

- [ ] Discover possible race conditions in running multiple matching engines

**Comment by xuganyu96** [comment]
# Possible lock condition
During one of the benchmarking session with 4 matching engines running concurrently, two of the engines crashed because the same order was used as parent order of the same.

One approach would be to use a SQL table lock, but each SQL server implements table lock differently, and SQLite has no table lock at all, so using table lock is not practical.

Another approach would be to let SQLAlchemy raise SQL contrainst exception and handle the exception by rolling back all transactions of the session and restarting the heartbeat. While this will solve the problem where a single order is parent order of multiple other orders, it doesn't solve the problem where a single candidate can be used in multiple transactions. I can try to implement it but it is not a complete solution: othe race conditions could still occur.

A third approach would be to implement a table-level lock: add a `locked` column to the `orders` table, and each time `get_candidates` is called, all results queried will immediately have `locked` set to True (and `get_candidates` will add a filter to query only unlocked orders), and at the end of the heartbeat, release the locks by setting those candidates' lock back to False. However, there might be a lot of overhead if there are many candidates queried, and a second engine could still query a candidate before the first engine locks it up, so this measure only reduces the chance of the race condition, not eliminates it.
